- hosts: all
  remote_user: opc
  become: yes
  become_method: sudo

  tasks:

  - name: download new OCI repo
    get_url:
      url: http://yum-phx.oracle.com/yum-phx-ol7.repo
      dest: /etc/yum.repos.d/yum-phx-ol7.repo

  - name: install nginx
    yum:
      name:
      - nginx
      - certbot
      - python2-certbot-nginx
      state: installed

  - name: copy the nginx config file
    copy:
      src: ./nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: make web-app directory
    become: yes
    become_method: sudo
    file:
      path: /var/www/virtual/webapp/
      state: directory
      mode: 0755

  - name: copy app web artifacts
    become: yes
    become_method: sudo
    copy:
      src: ../htdocs
      dest: /var/www/virtual/webapp/

  - name: nginx verify
    become: yes
    become_method: sudo
    command: nginx -t

  - name: nginx restart
    become: yes
    become_method: sudo
    command: systemctl start nginx

  - name: allow http/s service
    become: yes
    become_method: sudo
    command: firewall-cmd --permanent --zone=public --add-service=http --add-service=https

  - name: bounce firewall
    command: firewall-cmd --reload