- hosts: all
  remote_user: opc
  become: yes
  become_method: sudo

  tasks:

  - name: download new OCI repo
    get_url:
      url: http://yum-phx.oracle.com/yum-phx-ol7.repo
      dest: /etc/yum.repos.d/yum-phx-ol7.repo

  - name: install nginx
    yum:
      name:
      - nginx
      - certbot
      - python2-certbot-nginx
      state: installed

  - name: make sites-available directory
    become: yes
    become_method: sudo
    file:
      path: /etc/nginx/sites-available/
      state: directory

  - name: make sites-enabled directory
    become: yes
    become_method: sudo
    file:
      path:  /etc/nginx/sites-enabled/
      state: directory

  - name: copy the nginx app config file
    become: yes
    become_method: sudo
    copy:
      src: app.cfg
      dest: /etc/nginx/sites-available/app.cfg
      become: yes

  - name: create symlink
    become: yes
    become_method: sudo
    file:
      src: /etc/nginx/sites-available/app.cfg
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: copy app web artifacts
    become: yes
    become_method: sudo
    copy:
      src: ../app
      dest: /home/opc

  - name: nginx verify
    become: yes
    become_method: sudo
    command: nginx -t

  - name: nginx restart
    become: yes
    become_method: sudo
    command: systemctl start nginx

  - name: allow http/s service
    become: yes
    become_method: sudo
    command: firewall-cmd --permanent --zone=public --add-service=http --add-service=https

  - name: bounce firewall
    command: firewall-cmd --reload