- hosts: all
  remote_user: opc
  become: yes
  become_method: sudo
  gather_facts: True

  vars:
    host_ip: {{ ansible_default_ipv4.address }}

  tasks:

  - name: Gather facts from new server
    setup:
      filter: ansible_default_ipv4.address

  - name: download new OCI repo
    get_url:
      url: http://yum-phx.oracle.com/yum-phx-ol7.repo
      dest: /etc/yum.repos.d/yum-phx-ol7.repo

  - name: install nginx
    yum:
      name:
      - nginx
      - certbot
      - python2-certbot-nginx
      state: installed

  - name: Ansible Template Example
    template:
      src: nginx.conf.j2
      dest: nginx.conf

  - name: copy the nginx config file
    copy:
      src: ./nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: copy app web artifacts
    become: yes
    become_method: sudo
    copy:
      src: ../html
      dest: /usr/share/nginx
      mode: 0755

  - name: nginx verify
    become: yes
    become_method: sudo
    command: nginx -t

  - name: nginx restart
    become: yes
    become_method: sudo
    command: systemctl start nginx

  - name: allow http/s service
    become: yes
    become_method: sudo
    command: firewall-cmd --permanent --zone=public --add-service=http --add-service=https

  - name: bounce firewall
    command: firewall-cmd --reload