- hosts: all
  remote_user: opc
  become: yes
  become_method: sudo

  tasks:

  - name: download new OCI repo
    get_url:
      url: http://yum-phx.oracle.com/yum-phx-ol7.repo
      dest: /etc/yum.repos.d/yum-phx-ol7.repo

  - name: install nginx
    yum:
      name:
      - nginx
      - certbot
      - python2-certbot-nginx
      state: installed

  - name: make web-app directory
    become: yes
    become_method: sudo
    file:
      path: /var/www/supliz.io
      state: directory

  - name: copy the web-app config file to conf.d
    copy:
      src: ./supliz.io.conf
      dest: /etc/nginx/conf.d/supliz.io.conf

  - name: copy app web artifacts
    become: yes
    become_method: sudo
    copy:
      src: ../app
      dest: /var/www/supliz.io

  - name: nginx verify
    become: yes
    become_method: sudo
    command: nginx -t

  - name: nginx restart
    become: yes
    become_method: sudo
    command: systemctl start nginx

  - name: allow http/s service
    become: yes
    become_method: sudo
    command: firewall-cmd --permanent --zone=public --add-service=http --add-service=https

  - name: bounce firewall
    command: firewall-cmd --reload