- hosts: all
  remote_user: opc
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml

  tasks:
  - debug: var=ansible_all_ipv4_addresses
  - debug: var=ansible_default_ipv4.address

  - name: download new OCI repo
    get_url:
      url: http://yum-phx.oracle.com/yum-phx-ol7.repo
      dest: /etc/yum.repos.d/yum-phx-ol7.repo

  - name: install nginx
    yum:
      name:
      - nginx
      - certbot
      - python2-certbot-nginx
      state: installed

  - template:
      src: ./nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      force: true
      become: true

  - name: copy app web artifacts
    become: yes
    become_method: sudo
    copy:
      src: ../html
      dest: /usr/share/nginx
      mode: 0755

  - name: nginx verify
    become: yes
    become_method: sudo
    command: nginx -t

  - name: nginx restart
    become: yes
    become_method: sudo
    command: systemctl start nginx

  - name: allow http/s service
    become: yes
    become_method: sudo
    command: firewall-cmd --permanent --zone=public --add-service=http --add-service=https

  - name: bounce firewall
    command: firewall-cmd --reload